# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-DisableForm
version:      0.01
version_from: lib/HTML/DisableForm.pm
installdirs:  site
requires:
    HTML::Parser:                  3.26
    Test::More:                    0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
